### ISSUE TITLE
[Idea] Add backups

### ISSUE THREAD

**Issue by x9nico** [NichtStudioCode/MiniatureBlocks#7]
Hi, it could be cool to add something in config files to make backups of our miniatureblocks (to save coordinates)
It could be in a config file or save it in a MySQL's database (It could be very interesting for me in a DB because I'm running multiple servers and I would like to syncronize across servers).

**Comment by NichtStudioCode** [comment]
So you basically want BungeeCord support?

**Comment by x9nico** [comment]
> So you basically want BungeeCord support?

I'm not running BungeeCord, I'm running Velocity.
But, it's preferable to use MySQL for this.

**Comment by NichtStudioCode** [comment]
I don't really understand what you're trying to do. Why would you want to save coordinates? I'd understand it if you'd want to synchronize the models across servers but why coordinates? Also, the miniatures are just armor stands in the world so you could just copy the world if thats what you're trying to do.

**Comment by x9nico** [comment]
> I don't really understand what you're trying to do. Why would you want to save coordinates? I'd understand it if you'd want to synchronize the models across servers but why coordinates? Also, the miniatures are just armor stands in the world so you could just copy the world if thats what you're trying to do.

It's to sync and save coordinates :)

**Comment by NichtStudioCode** [comment]
> It's to sync and save coordinates :)

Yes, I don't understand why you'd want to do that.

**Comment by x9nico** [comment]
> > It's to sync and save coordinates :)
> 
> Yes, I don't understand why you'd want to do that.

I'm running Multiple Hubs servers with somes MiniatureBlocks at somes coordinates. It could be more easiler to sync them.

**Comment by NichtStudioCode** [comment]
Shouldn't you be able to just copy the world then?

**Comment by x9nico** [comment]
> Shouldn't you be able to just copy the world then?

No, because I want to update it automatically.

**Comment by NichtStudioCode** [comment]
As I've already mentioned previously, the miniatures are just armor stands inside the world. In order to extract their locations one would have to loop over every generated chunk and check every entity if they're a miniature.
Personally, I haven’t worked much with server networks but I know that normally, you should have some kind of template server which gets automatically copied when something changes.
I would understand the need of synchronizing the models across a network, but even that is currently not on top of my to-do list.
